# Generated by Django 2.2.16 on 2020-10-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=255, null=True)),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_app.Room')),
            ],
            options={
                'unique_together': {('id_room', 'date')},
            },
        ),
    ]
