# Generated by Django 2.2.16 on 2020-10-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0003_auto_20201017_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id_room',
            new_name='room',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room', 'date')},
        ),
    ]
